services:
  - type: web
    name: churn-api
    env: docker
    rootDir: bank-churn-prediction-main
    region: frankfurt
    plan: free
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CHURN_API_KEY
        generateValue: true

  - type: web
    name: churn-dashboard
    env: docker
    rootDir: bank-churn-prediction-main
    region: frankfurt
    plan: free
    dockerCommand: streamlit run dashboard.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: CHURN_API_KEY
        fromService:
          type: web
          name: churn-api
          envVarKey: CHURN_API_KEY
      - key: API_URL
        fromService:
          type: web
          name: churn-api
          envVarKey: RENDER_EXTERNAL_URL
